version: '3.8'
services:
  java-maven-app:
    image: opeyemiagbadero/demo-app:jma-5.0
    ports:
      - 8080:8080
  postgress:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD:my-pwd

