version: '3.8'

services:
  java-maven-app:
    image: opeyemiagbadero/demo-app:jma-5.0
    ports:
      - 8080:8080

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd

